CREATE TABLE SUPERHEROES(
    SH_NAME VARCHAR2(20),

);

SET SERVEROUTPUT ON;
CREATE OR REPLACE TRIGGER SUPERHERO_TRIG
BEFORE INSERT ON SUPERHEROES
FOR EACH ROW
ENABLE

DECLARE
  V_USER VARCHAR2(20);

BEGIN
  SELECT USER INTO V_USER FROM DUAL;
  DBMS_OUTPUT.PUT_LINE('You Just Inserted A Line ' || V_USER);
END;
/


-------
CREATE OR REPLACE TRIGGER SUPERHERO_TRIG
BEFOR INSERT OR UPDATE OR DELETE ON SUPERHEROES
FOR EACH ROW
ENABLE 

DECLARE
  V_USER VARCHAR2(20);
BEGIN
  SELECT USER INTO V_USER FROM DUAL;
  IF INSETING THEN
    DBMS_OUTPUT.PUT_LINE('INSERTION PERFORMED BY '||V_USER);
  ELSIF DELETING THEN
    DBMS_OUTPUT.PUT_LINE('DELETION PERFORMED BY '||V_USER);
  ELSIF UPDATING THEN
    DBMS_OUTPUT.PUT_LINE('UPDATE PERFORMED BY '||V_USER);
  ENDIF;
END;
/



---GLOBAL TRIGGER

CREATE OR REPLACE TRIGGER UPDATE_EMP_SAL
AFTER INSERT OR UJPDATE OF SALARY ON EMPLOYEE
FOR EACH ROW 

BEGIN
  UPDATE DEPARTMENT
  SET TOTAL_SALARY = TOTAL_SALARY+ :NEW.SALARY - :OLD.SALARY;
  WHERE DEPARTMENT_ID = :NEW.DEPARTMENT_ID;
END;
/