--TABLE CREATION - TASK-1
CREATE TABLE ACCOUNT
(
   ACCOUNT_NO CHAR(5),
   BALANCE NUMBER NOT NULL,
   CONSTRAINT PK_ACCOUNT PRIMARY KEY(ACCOUNT_NO)
);
CREATE TABLE CUSTOMER
(
    CUSTOMER_NO CHAR(5),
    CUSTOMER_NAME VARCHAR2(20) NOT NULL,
    CUSTOMER_CITY VARCHAR2(10),
    CONSTRAINT PK_CUSTOMER PRIMARY KEY(CUSTOMER_NO)
);
CREATE TABLE DEPOSITOR
(
    ACCOUNT_NO CHAR(5),
    CUSTOMER_NO CHAR(5),
    CONSTRAINT PK_DEPOSITOR PRIMARY KEY(ACCOUNT_NO,CUSTOMER_NO)
);

--TASK-2
ALTER TABLE CUSTOMER ADD DATE_OF_BIRTH DATE;
ALTER TABLE ACCOUNT MODIFY BALANCE NUMBER(12,2);
ALTER TABLE CUSTOMER RENAME COLUMN CUSTOMER_NO TO C_NO;
ALTER TABLE ACCOUNT RENAME COLUMN ACCOUNT_NO TO A_NO;
RENAME DEPOSITOR TO DEPOSITOR_INFO;

ALTER TABLE DEPOSITOR_INFO
ADD CONSTRAINT FK_DEPOSITOR_ACCOUNT
FOREIGN KEY (A_NO) REFERENCES ACCOUNT(A_NO);

ALTER TABLE DEPOSITOR_INFO
ADD CONSTRAINT FK_DEPOSITOR_CUSTOMER
FOREIGN KEY (C_NO) REFERENCES CUSTOMER(C_NO);

--TASK-3
SELECT A_NO FROM ACCOUNT
WHERE BALANCE>100000;

SELECT CUSTOMER_NAME FROM CUSTOMER
WHERE CUSTOMER_CITY = 'Dhaka';

SELECT DISTINCT A_NO FROM DEPOSITOR_INFO;

SELECT *
FROM ACCOUNT, DEPOSITOR_INFO;

SELECT *
FROM CUSTOMER NATURAL JOIN DEPOSITOR_INFO ;

SELECT CUSTOMER_NAME,CITY WHERE A_NO = NOT NULL;



