CREATE OR REPLACE TRIGGER TRG_ACCOUNT_ID_GEN
BEFORE INSERT ON ACCOUNT
FOR EACH ROW
BEGIN
  SELECT ACCOUNT_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  :NEW.ID := 
    TO_CHAR(:NEW.ACCCODE) ||
    TO_CHAR(TO_DATE(:NEW.OPENINGDATE,'YYYY-MM-DD'),'YYYYMMDD') ||
    SUBSTR(:NEW.NAME,1,3) ||
    LPAD(:NEW.ID, 6, '0');
END;
/

