DELETE FROM ACCOUNT
ALTER TABLE ACCOUNT DROP COLUMN ID CASCASDE CONSTRAINTS;
ALTER TABLE ACCOUNT ADD ID VARCHAR2(25) PRIMARY KEY;

DELETE FROM BALANCE
ALTER TABLE BALANCE DROP COLUMN ACCNO CASCASDE CONSTRAINTS;
ALTER TABLE BALANCE ADD ACCNO VARCHAR2(25) PRIMARY KEY REFERENCES ACCOUNT;

DELETE FROM TRANSACTION
ALTER TABLE TRANSACTION DROP COLUMN ACCNO CASCASDE CONSTRAINTS;
ALTER TABLE TRANSACTION ADD ACCNO VARCHAR2(25) REFERENCES ACCOUNT;
