CREATE TABLE CUSTOMERS(
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PREFERRED_FOOD VARCHAR(255) NOT NULL,
    FOREIGN KEY(PREFERRED_FOOD) REFERENCES MENUS(NAME);
);


CREATE TABLE FRANCHISES(
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
);


CREATE TABLE BRANCHES (
    ID INTEGER PRIMARY KEY,
    FRANCHISE_ID INTEGER NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    FOREIGN KEY (FRANCHISE_ID) REFERENCES FRANCHISES(ID)
);


CREATE TABLE CHEFS(
    ID INTEGER PRIMARY KEY,
    BRANCH_ID INTEGER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CUISINE VARCHAR(255) NOT NULL,
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(ID)
);


CREATE TABLE MENUS (
    ID INTEGER PRIMARY KEY,
    CHEF_ID INTEGER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CUISINE VARCHAR(255) NOT NULL,
    MAIN_INGREDIENTS VARCHAR(255) NOT NULL,
    PRICE DECIMAL NOT NULL,
    CALORIE_COUNT INTEGER NOT NULL,
    FOREIGN KEY (CHEF_ID) REFERENCES CHEFS(ID)
);


CREATE TABLE ORDERS(
    ID INTEGER PRIMARY KEY,
    CUSTOMER_ID INTEGER NOT NULL,
    MENU_ID INTEGER NOT NULL,
    BRANCH_ID INTEGER NOT NULL,
    ORDER_DATE DATE NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    FOREIGN KEY (MENU_ID) REFERENCES MENUS(ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(ID)
);


CREATE TABLE CUSTOMER_RATINGS(
    ID INTEGER PRIMARY KEY,
    CUSTOMER_ID INTEGER NOT NULL,
    MENU_ID INTEGER NOT NULL,
    ORDER_ID INTEGER NOT NULL,
    RATING INTEGER NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    FOREIGN KEY (MENU_ID) REFERENCES MENUS(ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID)
);

