--a--
SELECT F.NAME, COUNT(C.ID) AS TOTAL_CUSTOMERS
FROM FRANCHISES F
LEFT JOIN BRANCHES B ON B.FRANCHISE_ID = F.ID
GROUP BY F.NAME;

--b--

SELECT M.NAME, AVG(CR.RATING) AS AVG_RATING
FROM MENUS M
NATURAL JOIN CUSTOMER_RATINGS CR ON CR.MENU_ID = M.ID
GROUP BY M.NAME
ORDER BY AVG_RATING DESC;

--c--

SELECT M.NAME, COUNT(O.ID) AS TIMES_ORDERED
FROM MENUS M
LEFT JOIN ORDERS O ON O.MENU_ID = M.ID
GROUP BY M.NAME
ORDER BY TIMES_ORDERED DESC
LIMIT 5;


--d--

SELECT C.NAME
FROM CUSTOMERS C
JOIN (
    SELECT PREFERRED_FOOD, COUNT(DISTINCT FRANCHISE_ID) AS NUM_FRANCHISES
    FROM (
        SELECT PREFERRED_FOOD, F.ID AS FRANCHISE_ID
        FROM CUSTOMERS C
        JOIN MENUS M ON M.CUISINE = C.PREFERRED_FOOD
        JOIN CHEFS CH ON CH.ID = M.CHEF_ID
        JOIN BRANCHES B ON B.ID = CH.BRANCH_ID
        JOIN FRANCHISES F ON F.ID = B.FRANCHISE_ID
    ) T
    
    GROUP BY PREFERRED_FOOD
    HAVING NUM_FRANCHISES >= 2
)
T ON T.PREFERRED_FOOD = C.PREFERRED_FOOD;  
    

--e--

SELECT C.NAME
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON O.CUSTOMER_ID = C.ID
WHERE O.ID IS NULL



